server:
  port: 8088
  servlet:
    context-path: /file-process

spring:
  servlet:
    multipart:
      max-file-size: 100GB  #单个文件数据大小
      max-request-size: 1000GB #总文件大小
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:sqlite/dexample.db

sys:
  rootPath: C:\Users\Administrator\Desktop
  rootDir: C:\Users\Administrator\Desktop
  uploadRootPath: C:\Users\Administrator\Desktop

value:
  static:
    path-pattern: /static/file/**
    static-locations: file:c:/